library = Library()
library.add_book("Python Crash Course", "Eric Matthes")
library.add_book("Atomic Habits", "James Clear")
library.add_book("Deep Work", "Cal Newport")
library.view_books()
print("\n-- Issue --")
library.issue_book(1)
library.view_books()
print("\n-- Return --")
library.return_book(1)
print("\n-- Remove --")
library.remove_book(2)
library.view_books()